# Generated by Django 3.1.7 on 2021-03-06 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models.event
import tickets.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "tickets_type",
                    tickets.utils.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("regular", "Regular ticket"),
                                ("premium", "Premium ticket"),
                                ("vip", "Vip ticket"),
                            ],
                            max_length=30,
                        ),
                        default=tickets.models.event.get_default_ticket,
                        size=None,
                        verbose_name="Tickets type",
                    ),
                ),
                (
                    "regular_tickets_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Regular tickets quantity"),
                ),
                (
                    "regular_tickets_price",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Regular tickets price"),
                ),
                (
                    "premium_tickets_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Premium tickets quantity"),
                ),
                (
                    "premium_tickets_price",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Premium tickets price"),
                ),
                (
                    "vip_tickets_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="VIP tickets quantity"),
                ),
                (
                    "vip_tickets_price",
                    models.PositiveSmallIntegerField(default=0, verbose_name="VIP tickets price"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is event active"),
                ),
                ("started_at", models.DateTimeField(verbose_name="Event time")),
            ],
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Is ticket paid"),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=False, verbose_name="Is ticket reserved"),
                ),
                (
                    "reservation_expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Reservation expires at"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular ticket"),
                            ("premium", "Premium ticket"),
                            ("vip", "Vip ticket"),
                        ],
                        max_length=30,
                        verbose_name="Ticket type",
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Price"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"verbose_name": "Ticket", "verbose_name_plural": "Tickets"},
        ),
    ]
