# Generated by Django 3.1.7 on 2021-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_disabled",
            field=models.BooleanField(default=False, verbose_name="Is ticket disabled"),
        )
    ]
